version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:80"
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=localhost;Database=projetofastcash;User=root;Password=1234;
    restart: always

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: transacoes
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3307:3306"
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5